CREATE_DATE = "create_date"
UPDATE_DATE = "update_date"
EXPIRY_DATE = "expiry_date"
VALID_DURATION = "valid_duration"
REGISTRANT_COUNTRY = "registrant_country"
ADMIN_COUNTRY = "admin_country"
ADMIN_REGION = "admin_region"
CATEGORIES = "categories"
